name: pytest bash

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pytest-bash:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: bash -c "python -c 'import sys; print(sys.version)'"

      - name: Install dependencies
        run: |
          bash -c "pip install --upgrade pip coverage pytest"

      - name: Install package
        run: bash -c "pip install ."

      - name: Test with pytest
        run: export SHELL="/bin/bash" && bash -c "pytest"
